spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ctf_kt_0
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
